on:
  rss:
    url: https://getpocket.com/users/${{ secrets.POCKET_USERNAME }}/feed/unread

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://contrun.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= contrun.cachix.org-1:je0xqCRowN4w8BPKw3dOQvKxaINmfnJjVnzwfLYIiKQ=

      - name: Save to wallabag
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
          POCKET_USERNAME: ${{ secrets.POCKET_USERNAME }}
          WALLABAG_URL: "${{ secrets.WALLABAG_URL }}"
          WALLABAG_CLIENT_ID: "${{ secrets.WALLABAG_CLIENT_ID }}"
          WALLABAG_CLIENT_SECRET: "${{ secrets.WALLABAG_CLIENT_SECRET }}"
          WALLABAG_USERNAME: ${{ secrets.WALLABAG_USERNAME }}"
          WALLABAG_PASSWORD: "${{ secrets.WALLABAG_PASSWORD }}"
        run: |
          if ! nix run 'github:contrun/infra#wallabag-saver' -- -- "$link"; then
              >&2 echo "failed to save article"
              >&2 echo "title: $title"
              >&2 echo "contentSnippet: $contentSnippet"
              >&2 echo "link: $link"
          fi
